export interface BranchChoice {
  text: string;
  feedback: string;
  consequence: "positive" | "negative" | "neutral";
  xpDelta?: number;
}

export interface SeedLesson {
  stepId: string;
  type: "story" | "quiz" | "mini-game" | "challenge";
  title: string;
  ageGroup: "A" | "B" | "ALL";
  stepCategory: "intro" | "core" | "review" | "bridge" | "capstone";
  depthLevel: 1 | 2 | 3 | 4 | 5 | 6;
  text?: string;
  question?: string;
  options?: string[];
  answer?: number;
  explanation?: string;
  icon?: string;
  mascot?: string;
  speech?: string;
  conceptKeys?: string[];
  choices?: BranchChoice[];
  learningObjectives?: string[];
  successCriteria?: string[];
  connexusStandards?: string[];
  activityType?: string;
  materials?: string[];
}

export interface SeedLecture {
  slug: string;
  title: string;
  subtitle: string;
  icon: string;
  color: string;
  badge: string;
  badgeName: string;
  order: number;
  lessons: SeedLesson[];
}

export const SEED_LECTURES: SeedLecture[] = [
  // ─────────────────────────────────────────────────────────
  // MODULE 1 — CyberSafe World
  // ─────────────────────────────────────────────────────────
  {
    slug: "cybersafe-world",
    title: "CyberSafe World",
    subtitle: "Your adventure begins",
    icon: "🌍",
    color: "#4D96FF",
    badge: "🗺️",
    badgeName: "Explorer",
    order: 1,
    lessons: [
      // ── GROUP A (ages 6-8) ──
      {
        stepId: "a-module-intro-1",
        type: "story",
        title: "Your adventure begins",
        ageGroup: "A",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Welcome to CyberSafe World! Imagine the internet is a huge playground. There are fun games, friendly faces, and hidden dangers. Captain Cyber will be your guide. Together we will learn how to explore safely and protect ourselves. Are you ready?",
        icon: "🌍",
        mascot: "🦸",
        speech: "Every great explorer needs a map. This is yours — let's begin!",
        conceptKeys: ["internet_awareness", "module_intro"],
        learningObjectives: ["Understand the internet as a world with safe and unsafe areas","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-meet-captain",
        type: "story",
        title: "Meet Captain Cyber",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 1,
        text: "Captain Cyber knows the internet like a treasure map. He knows where the fun places are and where the tricky spots hide. He is here to show you the safe paths.",
        icon: "🦸",
        mascot: "🦸",
        speech: "Hi! I'm Captain Cyber. I will teach you to be an internet explorer.",
        conceptKeys: ["internet_awareness"],
        learningObjectives: ["Understand the internet as a world with safe and unsafe areas"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-what-is-personal-info",
        type: "story",
        title: "What is personal info?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "Your name, address, school, and phone number are private. They are like treasure — only share them with people you and your family trust. A stranger online does not need to know them.",
        icon: "🔒",
        mascot: "🦸",
        speech: "Your private info is treasure. Keep it safe!",
        conceptKeys: ["pii_basics"],
        learningObjectives: ["Identify personally identifiable information"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-safe-or-not-safe",
        type: "quiz",
        title: "Safe or not safe?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        question: "You are playing a game and a new player asks 'What is your full name and school?' What do you do?",
        options: [
          "Tell them — they seem friendly",
          "Do not tell them; tell a grown-up",
          "Only tell them your first name"
        ],
        answer: 1,
        explanation: "A new player should never get your full name and school. That is personal information. Tell a trusted adult instead.",
        icon: "🛡️",
        conceptKeys: ["pii_basics", "stranger_online"],
        learningObjectives: ["Identify personally identifiable information","Recognise risks from unknown people online"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-magic-door-rule",
        type: "story",
        title: "The magic door rule",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "If a stranger online asks for your private information, imagine they are at your front door. What would you do? Close the door and tell a grown-up! The same rule applies online.",
        icon: "🚪",
        mascot: "🦸",
        speech: "When in doubt, close the door and find an adult.",
        conceptKeys: ["stranger_online", "tell_adult"],
        learningObjectives: ["Recognise risks from unknown people online","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-who-to-tell",
        type: "quiz",
        title: "Who should you tell?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        question: "A stranger online keeps asking for your address. Who is the right person to tell?",
        options: ["A stranger", "Your teacher or parent", "No one — it is not a big deal"],
        answer: 1,
        explanation: "Always tell a trusted adult. They will help you stay safe.",
        icon: "👨‍👩‍👧",
        conceptKeys: ["tell_adult", "stranger_online"],
        learningObjectives: ["Know when and how to ask a trusted adult for help","Recognise risks from unknown people online"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-module1-review",
        type: "quiz",
        title: "Module 1 review",
        ageGroup: "A",
        stepCategory: "review",
        depthLevel: 3,
        question: "Which of these is the safest thing to do when someone online asks for your school name?",
        options: [
          "Tell them and ask what they want",
          "Do not tell them and tell a grown-up",
          "Tell a friend instead"
        ],
        answer: 1,
        explanation: "Keeping your school name private and telling an adult is always the safest choice.",
        icon: "📝",
        conceptKeys: ["pii_basics", "stranger_online", "tell_adult"],
        learningObjectives: ["Identify personally identifiable information","Recognise risks from unknown people online","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-module1-bridge",
        type: "story",
        title: "Your real-world mission",
        ageGroup: "A",
        stepCategory: "bridge",
        depthLevel: 4,
        text: "In the next 24 hours, find one real example of something you should keep private (like a school name or address). Tell a grown-up about it. If they confirm you did, Captain Cyber will reward you with extra gems!",
        icon: "🌍",
        mascot: "🦸",
        speech: "Learning does not stop at the screen. Real safety starts in real life.",
        conceptKeys: ["pii_basics", "tell_adult", "real_world_bridge"],
        learningObjectives: ["Identify personally identifiable information","Know when and how to ask a trusted adult for help","Connect online learning to offline habits"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-module1-capstone",
        type: "quiz",
        title: "Explorer quiz",
        ageGroup: "A",
        stepCategory: "capstone",
        depthLevel: 4,
        question: "A message from a stranger says 'I have a gift for you — what is your home address?' What is the best answer?",
        options: [
          "Give the address and wait for the gift",
          "Do not answer and tell a parent",
          "Give only your street name"
        ],
        answer: 1,
        explanation: "Strangers should never get your address. Always tell a parent or guardian.",
        icon: "🏆",
        conceptKeys: ["pii_basics", "stranger_online", "tell_adult"],
        learningObjectives: ["Identify personally identifiable information","Recognise risks from unknown people online","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      // ── GROUP B (ages 8-12) ──
      {
        stepId: "b-module-intro-1",
        type: "story",
        title: "Enter the grid",
        ageGroup: "B",
        stepCategory: "intro",
        depthLevel: 1,
        text: "The internet is not one thing — it is a billion places. Some are bright marketplaces, some are dark alleys. You cannot tell by looking. In this module, you will learn to map the terrain, read the signs, and move with confidence.",
        icon: "🌍",
        mascot: "🦸",
        speech: "A explorer who knows the terrain never gets lost. Let's draw your map.",
        conceptKeys: ["internet_awareness", "digital_footprint", "module_intro"],
        learningObjectives: ["Understand the internet as a world with safe and unsafe areas","Understand that online actions leave a permanent trail","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-digital-footprint-basics",
        type: "quiz",
        title: "Digital footprint basics",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 2,
        question: "You post a photo on a public account. Three weeks later, a stranger screenshots it and uses it in a fake profile. Why does this happen?",
        options: [
          "The app deleted your photo",
          "Once something is online, it can be copied and shared beyond your control",
          "Your phone was hacked"
        ],
        answer: 1,
        explanation: "Your digital footprint is permanent. Assume anything you post can be shared widely.",
        icon: "👣",
        conceptKeys: ["digital_footprint"],
        learningObjectives: ["Understand that online actions leave a permanent trail"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-avatar-creation",
        type: "story",
        title: "Avatar creation",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 1,
        text: "Your online identity is yours to shape. Choose wisely — your avatar represents you in the CyberSafe World and reminds you that your digital self matters.",
        icon: "👤",
        mascot: "🦸",
        speech: "Your avatar is your digital self. Make it yours!",
        conceptKeys: ["online_identity"],
        learningObjectives: ["Understand that your digital self matters"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-pii-classification",
        type: "quiz",
        title: "PII classification",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        question: "You are signing up for a new game. It asks for your full name, birthdate, and home address. Which combination should you give?",
        options: [
          "All of it — the game needs to know",
          "Only what is required; never share address unless a parent approves",
          "Make up a fake name and real address"
        ],
        answer: 1,
        explanation: "Only share required information. Full address should never be shared without parental approval.",
        icon: "🪪",
        conceptKeys: ["pii_basics"],
        learningObjectives: ["Identify personally identifiable information"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-stranger-test",
        type: "story",
        title: "The stranger test",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "Before sharing anything online, ask: 'Would I say this to a stranger in real life?' If the answer is no, do not post it. This simple test stops most oversharing before it happens.",
        icon: "🧪",
        mascot: "🦸",
        speech: "The stranger test is your best filter.",
        conceptKeys: ["stranger_online", "pii_basics"],
        learningObjectives: ["Recognise risks from unknown people online","Identify personally identifiable information"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-social-post-analysis",
        type: "quiz",
        title: "Social post analysis",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        question: "A classmate posts: 'At home alone tonight — my address is 12 Oak Street. Come over!' What is wrong here, and what should they do?",
        options: [
          "Nothing — it is just a joke",
          "They overshared location and should delete the post + tell an adult",
          "They should just unfriend anyone who comments"
        ],
        answer: 1,
        explanation: "Sharing your address publicly is dangerous. The fix is delete + tell an adult, not just unfriending.",
        icon: "📱",
        conceptKeys: ["digital_footprint", "pii_basics", "tell_adult"],
        learningObjectives: ["Understand that online actions leave a permanent trail","Identify personally identifiable information","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-module1-review",
        type: "quiz",
        title: "Module 1 review",
        ageGroup: "B",
        stepCategory: "review",
        depthLevel: 3,
        question: "Which statement about your digital footprint is true?",
        options: [
          "You can delete anything you post whenever you want",
          "Once something is online, it can live forever even if you delete it",
          "Only adults have a digital footprint"
        ],
        answer: 1,
        explanation: "Digital footprints persist through screenshots, archives, and caches. Think before you post.",
        icon: "📝",
        conceptKeys: ["digital_footprint", "pii_basics", "stranger_online"],
        learningObjectives: ["Understand that online actions leave a permanent trail","Identify personally identifiable information","Recognise risks from unknown people online"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-module1-bridge",
        type: "story",
        title: "Real-world mission",
        ageGroup: "B",
        stepCategory: "bridge",
        depthLevel: 4,
        text: "This week, find one piece of personal information you almost shared online and tell a parent or guardian why you chose not to. If they confirm it, Captain Cyber will reward you with bonus gems. Real safety starts offline.",
        icon: "🌍",
        mascot: "🦸",
        speech: "Bridging online learning to real life is what makes a true Cyber Guardian.",
        conceptKeys: ["digital_footprint", "pii_basics", "real_world_bridge"],
        learningObjectives: ["Understand that online actions leave a permanent trail","Identify personally identifiable information","Connect online learning to offline habits"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-module1-capstone",
        type: "quiz",
        title: "Module challenge",
        ageGroup: "B",
        stepCategory: "capstone",
        depthLevel: 5,
        question: "You want to join a new online club. They ask for your school, age, and a photo. What is the safest approach?",
        options: [
          "Send everything — you trust the club",
          "Share only what is necessary; never send a photo without a parent checking first",
          "Send a fake photo and real school name"
        ],
        answer: 1,
        explanation: "Minimum necessary information plus parental involvement is the safest approach.",
        icon: "🏆",
        conceptKeys: ["digital_footprint", "pii_basics", "stranger_online", "tell_adult"],
        learningObjectives: ["Understand that online actions leave a permanent trail","Identify personally identifiable information","Recognise risks from unknown people online","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // MODULE 2 — The Bully Blocker
  // ─────────────────────────────────────────────────────────
  {
    slug: "bully-blocker",
    title: "The Bully Blocker",
    subtitle: "Stand up to cyberbullying",
    icon: "🛡️",
    color: "#FF7A59",
    badge: "💪",
    badgeName: "Defender",
    order: 2,
    lessons: [
      // ── GROUP A ──
      {
        stepId: "a-module-intro-2",
        type: "story",
        title: "A mean message",
        ageGroup: "A",
        stepCategory: "intro",
        depthLevel: 1,
        text: "One day, Captain Cyber received a message that made him feel sad. Someone had been unkind online — they did not know Captain Cyber, but they said something hurtful anyway. This is called cyberbullying. In this module, you will learn how to stop it and be a hero.",
        icon: "💬",
        mascot: "🦸",
        speech: "Even heroes need help sometimes. Let's learn how to be a Bully Blocker!",
        conceptKeys: ["cyberbullying_recognition", "module_intro"],
        learningObjectives: ["Identify signs of cyberbullying","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-cross-module-review-1",
        type: "quiz",
        title: "Review: CyberSafe World",
        ageGroup: "A",
        stepCategory: "review",
        depthLevel: 2,
        question: "Remember Module 1? If a stranger asks for your address in a game chat, what do you do?",
        options: [
          "Tell them politely",
          "Do not tell them and tell a grown-up",
          "Give a fake address"
        ],
        answer: 1,
        explanation: "The magic door rule still applies. Close the door and find an adult.",
        icon: "🛡️",
        conceptKeys: ["pii_basics", "stranger_online", "tell_adult"],
        learningObjectives: ["Identify personally identifiable information","Recognise risks from unknown people online","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-what-is-cyberbullying",
        type: "story",
        title: "What is cyberbullying?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "Cyberbullying is when someone is mean to another person using phones, games or messages. It can hurt feelings even through a screen. The person being bullied is never at fault.",
        icon: "💬",
        mascot: "🦸",
        speech: "If someone is unkind online, you can block them and tell a grown-up.",
        conceptKeys: ["cyberbullying_recognition"],
        learningObjectives: ["Identify signs of cyberbullying"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-block-and-tell",
        type: "story",
        title: "Block and tell",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        text: "When someone is mean to you online, the first thing to do is block them. Then tell a trusted adult — a parent, teacher, or Captain Cyber! Blocking stops the message. Telling stops the problem.",
        icon: "🚫",
        mascot: "🦸",
        speech: "Block first, tell second. That is the rule!",
        conceptKeys: ["cyberbullying_response"],
        learningObjectives: ["Know the correct response to online bullying"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-bully-quiz-1",
        type: "quiz",
        title: "Someone is being unkind…",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        question: "Your friend shows you a mean message they received. They say 'Let's send it back to them.' What do you do?",
        options: [
          "Help them send it back",
          "Tell them not to; help them block and tell an adult",
          "Laugh and share it with more friends"
        ],
        answer: 1,
        explanation: "Sending it back makes you part of the problem. Blocking and telling is the brave choice.",
        icon: "🚫",
        conceptKeys: ["cyberbullying_response", "bystander_intervention"],
        learningObjectives: ["Know the correct response to online bullying","Understand how to help as a bystander"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.3.d","ISTE 1.2.a"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-be-a-buddy",
        type: "story",
        title: "Be a buddy",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        text: "If you see a friend being bullied online, support them. Tell them to block the bully and then tell an adult together. A true defender does not watch from the sidelines.",
        icon: "🤝",
        mascot: "🦸",
        speech: "A true defender helps their friends.",
        conceptKeys: ["bystander_intervention"],
        learningObjectives: ["Understand how to help as a bystander"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-what-would-you-do",
        type: "quiz",
        title: "What would you do?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 4,
        question: "You see a classmate being bullied in a game chat. They have not told anyone. What is the best action?",
        options: [
          "Join the chat and defend them publicly",
          "Tell them privately to block and report, then tell an adult together",
          "Ignore it — it is not your business"
        ],
        answer: 1,
        explanation: "Privately supporting the victim and getting an adult involved is the safest, most effective response.",
        icon: "💪",
        conceptKeys: ["bystander_intervention", "cyberbullying_response"],
        learningObjectives: ["Understand how to help as a bystander","Know the correct response to online bullying"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-module2-review",
        type: "quiz",
        title: "Module 2 review",
        ageGroup: "A",
        stepCategory: "review",
        depthLevel: 3,
        question: "What are the two most important steps when someone is mean to you online?",
        options: [
          "Reply and block",
          "Block and tell a trusted adult",
          "Delete the app and cry"
        ],
        answer: 1,
        explanation: "Block first, tell second. Those two steps keep you safe and stop the bully.",
        icon: "📝",
        conceptKeys: ["cyberbullying_response", "bystander_intervention"],
        learningObjectives: ["Know the correct response to online bullying","Understand how to help as a bystander"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-module2-bridge",
        type: "story",
        title: "Your real-world mission",
        ageGroup: "A",
        stepCategory: "bridge",
        depthLevel: 4,
        text: "In the next 24 hours, think of someone who might be feeling left out or sad. Ask them to play a game with you. Being kind offline is just as important as being kind online. Tell a grown-up what you did!",
        icon: "🤝",
        mascot: "🦸",
        speech: "Kindness travels between the real world and the digital world.",
        conceptKeys: ["bystander_intervention", "cyberbullying_response", "real_world_bridge"],
        learningObjectives: ["Understand how to help as a bystander","Know the correct response to online bullying","Connect online learning to offline habits"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-module2-capstone",
        type: "quiz",
        title: "Defender quiz",
        ageGroup: "A",
        stepCategory: "capstone",
        depthLevel: 4,
        question: "A friend tells you someone is sending them mean messages. What is the FIRST thing you say?",
        options: [
          "Tell them to be stronger",
          "Show them how to block and offer to tell an adult together",
          "Tell them to send a mean message back"
        ],
        answer: 1,
        explanation: "A true defender helps with action, not advice to fight back.",
        icon: "🏆",
        conceptKeys: ["bystander_intervention", "cyberbullying_response"],
        learningObjectives: ["Understand how to help as a bystander","Know the correct response to online bullying"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      // ── GROUP B ──
      {
        stepId: "b-module-intro-2",
        type: "story",
        title: "The invisible bully",
        ageGroup: "B",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Someone types something cruel and hits send. In a second, someone else feels small. The worst part? The bully might be a stranger, a 'friend', or completely anonymous. Cyberbullying is real, it is common, and it is not your fault. In this module, you will learn how to stand up — for yourself and for others.",
        icon: "💬",
        mascot: "🦸",
        speech: "Courage is not about fighting. It is about doing the right thing when it matters.",
        conceptKeys: ["cyberbullying_recognition", "bystander_intervention", "module_intro"],
        learningObjectives: ["Identify signs of cyberbullying","Understand how to help as a bystander","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-cross-module-review-1",
        type: "quiz",
        title: "Review: CyberSafe World",
        ageGroup: "B",
        stepCategory: "review",
        depthLevel: 2,
        question: "From Module 1: you posted a photo and now it is being shared without your permission. What does this teach you about digital footprints?",
        options: [
          "Nothing — it is just a photo",
          "Once content is online, you lose some control over it",
          "You can always delete it completely"
        ],
        answer: 1,
        explanation: "Digital footprints persist. This is why Module 1 taught you to think before you post.",
        icon: "🛡️",
        conceptKeys: ["digital_footprint", "pii_basics", "stranger_online"],
        learningObjectives: ["Understand that online actions leave a permanent trail","Identify personally identifiable information","Recognise risks from unknown people online"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-anonymous-message",
        type: "story",
        title: "The anonymous message",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 2,
        text: "A new student receives an anonymous message: 'No one likes you here.' Even though the sender is hidden, the hurt is real. This is cyberbullying. Anonymity does not make cruelty acceptable.",
        icon: "💬",
        mascot: "🦸",
        speech: "Anonymity does not make cruelty acceptable.",
        conceptKeys: ["cyberbullying_recognition", "anonymity_risk"],
        learningObjectives: ["Identify signs of cyberbullying","Understand anonymity does not excuse cruelty"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-bystander-choice",
        type: "quiz",
        title: "Bystander choice",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        question: "You see a classmate being bullied in a group chat. What do you do?",
        options: [
          "Join in to avoid being targeted",
          "Privately message the victim, report the bully, and tell a teacher",
          "Ignore it — not my problem"
        ],
        answer: 1,
        explanation: "Bystanders have power. Reporting and supporting the victim breaks the cycle.",
        icon: "⚖️",
        conceptKeys: ["bystander_intervention"],
        learningObjectives: ["Understand how to help as a bystander"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-evidence-and-report",
        type: "story",
        title: "Evidence and report",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "Screenshots are evidence. Most platforms have a 'Report' button. Reporting is not tattling — it is protecting yourself and others. Screenshots + report = the strongest response.",
        icon: "📸",
        mascot: "🦸",
        speech: "Document. Report. Protect.",
        conceptKeys: ["cyberbullying_response", "platform_tools"],
        learningObjectives: ["Know the correct response to online bullying","Use block, report, and screenshot tools"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-platform-response",
        type: "quiz",
        title: "Platform response",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        question: "You are being cyberbullied in a game chat. The bully is anonymous. What is your best sequence of actions?",
        options: [
          "Reply with insults, then block",
          "Screenshot the messages, block the bully, report to the platform, and tell an adult",
          "Delete the game and never play again"
        ],
        answer: 1,
        explanation: "Screenshot + block + report + tell adult covers evidence, stopping the bully, platform action, and adult support.",
        icon: "📱",
        conceptKeys: ["cyberbullying_response", "platform_tools"],
        learningObjectives: ["Know the correct response to online bullying","Use block, report, and screenshot tools"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-bully-branch",
        type: "story",
        title: "The bystander branch",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        text: "You witness cyberbullying in a group chat. The bully is popular. Your choice will change what happens next.",
        icon: "🔀",
        mascot: "🦸",
        speech: "Every choice has a consequence. Choose wisely.",
        choices: [
          {
            text: "Join in to fit in",
            feedback: "The bully targets you next. The victim feels more alone. Your reputation suffers.",
            consequence: "negative",
            xpDelta: -10,
          },
          {
            text: "Privately support the victim and report the bully",
            feedback: "The victim thanks you. The bully is warned by moderators. You feel proud.",
            consequence: "positive",
            xpDelta: 25,
          },
          {
            text: "Ignore it and scroll away",
            feedback: "The bullying continues. Later, the victim tells an adult. You wish you had helped.",
            consequence: "neutral",
            xpDelta: 5,
          },
        ],
        conceptKeys: ["bystander_intervention", "cyberbullying_response", "anonymity_risk"],
        learningObjectives: ["Understand how to help as a bystander","Know the correct response to online bullying","Understand anonymity does not excuse cruelty"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-empathy-reboot",
        type: "story",
        title: "Empathy reboot",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "Sometimes bullies are struggling themselves. That does not make their actions okay, but understanding why can help you respond calmly and seek help rather than retaliate.",
        icon: "🧠",
        mascot: "🦸",
        speech: "Empathy does not mean accepting cruelty. It means you understand it so you can respond better.",
        conceptKeys: ["empathy", "bystander_intervention"],
        learningObjectives: ["Develop empathy while maintaining boundaries","Understand how to help as a bystander"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-bully-blocker-round",
        type: "quiz",
        title: "Bully blocker round",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 5,
        question: "A friend is being bullied online. The bully is anonymous. Your friend is scared to tell an adult. What do you do?",
        options: [
          "Tell them to ignore it",
          "Offer to go with them to tell a teacher, and screenshot the evidence",
          "Message the bully back"
        ],
        answer: 1,
        explanation: "Screenshot evidence + adult support is the strongest response. You become the bridge.",
        icon: "🤝",
        conceptKeys: ["bystander_intervention", "cyberbullying_response", "platform_tools"],
        learningObjectives: ["Understand how to help as a bystander","Know the correct response to online bullying","Use block, report, and screenshot tools"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-module2-review",
        type: "quiz",
        title: "Module 2 review",
        ageGroup: "B",
        stepCategory: "review",
        depthLevel: 3,
        question: "What is the correct order of actions when you see cyberbullying?",
        options: [
          "Reply, block, then tell",
          "Screenshot, block, report, tell an adult",
          "Ignore, delete, then forget"
        ],
        answer: 1,
        explanation: "Evidence first, then block/report, then adult support. That sequence protects everyone.",
        icon: "📝",
        conceptKeys: ["cyberbullying_response", "bystander_intervention", "platform_tools"],
        learningObjectives: ["Know the correct response to online bullying","Understand how to help as a bystander","Use block, report, and screenshot tools"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-module2-bridge",
        type: "story",
        title: "Real-world mission",
        ageGroup: "B",
        stepCategory: "bridge",
        depthLevel: 4,
        text: "This week, ask a family member: 'Have you ever seen someone being treated unkindly online? What did they do?' Write down the best answer and share it with Captain Cyber for a reward.",
        icon: "🌍",
        mascot: "🦸",
        speech: "Real courage is practised offline before it is needed online.",
        conceptKeys: ["bystander_intervention", "cyberbullying_response", "real_world_bridge"],
        learningObjectives: ["Understand how to help as a bystander","Know the correct response to online bullying","Connect online learning to offline habits"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-module2-capstone",
        type: "quiz",
        title: "Defender exam",
        ageGroup: "B",
        stepCategory: "capstone",
        depthLevel: 5,
        question: "A bully creates a fake account to harass someone. The victim does not know who it is. What is the most effective action?",
        options: [
          "Create a fake account back",
          "Document everything, report the account, and support the victim to tell an adult",
          "Convince the victim to quit everything"
        ],
        answer: 1,
        explanation: "Documentation + platform report + adult support is the complete defence.",
        icon: "🏆",
        conceptKeys: ["cyberbullying_response", "bystander_intervention", "platform_tools", "anonymity_risk"],
        learningObjectives: ["Know the correct response to online bullying","Understand how to help as a bystander","Use block, report, and screenshot tools","Understand anonymity does not excuse cruelty"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // MODULE 3 — The Phishing Fisher
  // ─────────────────────────────────────────────────────────
  {
    slug: "phishing-fisher",
    title: "The Phishing Fisher",
    subtitle: "Catch the scams!",
    icon: "🎣",
    color: "#2BC48A",
    badge: "🐟",
    badgeName: "Scam Catcher",
    order: 3,
    lessons: [
      // ── GROUP A ──
      {
        stepId: "a-too-good-to-be-true",
        type: "story",
        title: "Too good to be true?",
        ageGroup: "A",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Captain Cyber got a message: 'You won a free tablet!' He did not even enter a competition. Someone was trying to trick him. This is called phishing — when someone uses bait to get your personal information.",
        icon: "🎣",
        mascot: "🦸",
        speech: "If it seems too good to be true, it usually is. Time to become a Phishing Fisher!",
        conceptKeys: ["phishing_hooks", "module_intro"],
        learningObjectives: ["Recognise bait messages and fake offers","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-click-or-ask",
        type: "quiz",
        title: "Click or ask?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        question: "You get a message: 'Click here to win a free tablet!' You did not enter any competition. What do you do?",
        options: [
          "Click right away — free stuff!",
          "Ask a grown-up first",
          "Share with all your friends"
        ],
        answer: 1,
        explanation: "Free prize messages are often scams. Always check with a grown-up!",
        icon: "🎁",
        conceptKeys: ["phishing_hooks", "tell_adult"],
        learningObjectives: ["Recognise bait messages and fake offers","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-strange-links",
        type: "story",
        title: "Strange links",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "Weird links are like suspicious doors. You would not open a door to a stranger — do not click a link from one either. Look for the little lock icon and web address that makes sense.",
        icon: "🔗",
        mascot: "🦸",
        speech: "Strange links = keep out!",
        conceptKeys: ["suspicious_links"],
        learningObjectives: ["Identify and avoid dangerous links"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-meet-the-phishing-fisher",
        type: "story",
        title: "The Phishing Fisher",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        text: "Meet the Phishing Fisher — he casts fake bait (prizes, warnings, fake logins) hoping you will bite. Your job is to spot his bait and throw it back.",
        icon: "🎣",
        mascot: "🦸",
        speech: "The Phishing Fisher is sneaky, but we are smarter!",
        conceptKeys: ["phishing_awareness"],
        learningObjectives: ["Understand phishing tactics and prevention"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-catch-or-throw-back",
        type: "quiz",
        title: "Catch or throw back?",
        ageGroup: "A",
        stepCategory: "capstone",
        depthLevel: 3,
        question: "Which message looks safest?",
        options: [
          "cool-free-prize.click",
          "your-school-website.org",
          "win-now-now.biz"
        ],
        answer: 1,
        explanation: "Strange or 'too fun' links are traps. Trust real, known websites.",
        icon: "🔗",
        conceptKeys: ["suspicious_links", "phishing_awareness"],
        learningObjectives: ["Identify and avoid dangerous links","Understand phishing tactics and prevention"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      // ── GROUP B ──
      {
        stepId: "b-prize-that-wasnt",
        type: "story",
        title: "The prize that wasn't",
        ageGroup: "B",
        stepCategory: "intro",
        depthLevel: 1,
        text: "You receive: 'Congratulations! You won an iPhone. Click here to claim.' The sender is 'support@apple-support.xyz'. Three red flags in one message: a prize you did not earn, a weird sender, and pressure to act fast.",
        icon: "🎣",
        mascot: "🦸",
        speech: "Legitimate companies do not give away iPhones in random DMs.",
        conceptKeys: ["phishing_hooks", "sender_spoofing"],
        learningObjectives: ["Recognise bait messages and fake offers","Recognise fake sender addresses"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-url-forensics",
        type: "quiz",
        title: "URL forensics",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 2,
        question: "You receive a link that looks like your school login. The real school site is your-school.org. Which URL is suspicious?",
        options: [
          "https://your-school.org/login",
          "https://your-school.secure-login.xyz",
          "https://google.com"
        ],
        answer: 1,
        explanation: "The domain 'secure-login.xyz' is not your-school.org. Always check the real domain before clicking.",
        icon: "🔍",
        conceptKeys: ["suspicious_links", "url_analysis"],
        learningObjectives: ["Identify and avoid dangerous links","Evaluate URLs for legitimacy"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-sender-spoofing",
        type: "story",
        title: "Sender spoofing",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "Scammers can make an email look like it comes from anyone. 'From: teacher@school.com' does not mean it is actually from your teacher. Always check the real email address, not just the display name.",
        icon: "🎭",
        mascot: "🦸",
        speech: "Never trust the 'From' name alone. Check the real address.",
        conceptKeys: ["sender_spoofing"],
        learningObjectives: ["Recognise fake sender addresses"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-urgency-trap",
        type: "quiz",
        title: "Urgency trap",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        question: "A message says 'Your account will be deleted in 1 hour unless you act now.' It asks for your password. What combination of tactics is this?",
        options: [
          "A normal security update",
          "Urgency + authority spoofing + credential harvesting",
          "A helpful reminder from your school"
        ],
        answer: 1,
        explanation: "This combines urgency, fake authority, and a password grab. Three red flags at once.",
        icon: "⏰",
        conceptKeys: ["urgency_tactics", "sender_spoofing", "phishing_hooks"],
        learningObjectives: ["Identify pressure tactics in scams","Recognise fake sender addresses","Recognise bait messages and fake offers"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-phishing-boss",
        type: "story",
        title: "The Phishing Fisher boss",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 5,
        text: "The Phishing Fisher combines all his tricks: a fake prize, a spoofed sender, a weird URL, and urgent language. Can you spot all four? This is the boss level — real scams use multiple tactics at once.",
        icon: "👑",
        mascot: "🦸",
        speech: "The boss level uses every trick. Stay sharp.",
        conceptKeys: ["phishing_hooks", "sender_spoofing", "suspicious_links", "urgency_tactics"],
        learningObjectives: ["Recognise bait messages and fake offers","Recognise fake sender addresses","Identify and avoid dangerous links","Identify pressure tactics in scams"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-catch-or-release",
        type: "quiz",
        title: "Catch or release",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        question: "Which message is safe?",
        options: [
          "You won a lottery! Click now!",
          "Your parent asked you to come home.",
          "Free coins for your game — enter password"
        ],
        answer: 1,
        explanation: "Only the message from a real, trusted person is safe.",
        icon: "🎣",
        conceptKeys: ["phishing_awareness", "sender_spoofing"],
        learningObjectives: ["Understand phishing tactics and prevention","Recognise fake sender addresses"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-phishing-forensics",
        type: "quiz",
        title: "Phishing forensics exam",
        ageGroup: "B",
        stepCategory: "capstone",
        depthLevel: 6,
        question: "You receive an email from 'bank@secure-bank.com' asking for your password. What do you do?",
        options: [
          "Reply with your password",
          "Call the bank using the number on their official website",
          "Click the link to verify your account"
        ],
        answer: 1,
        explanation: "Never give passwords via email. Call the real bank directly using their official number.",
        icon: "🕵️",
        conceptKeys: ["phishing_awareness", "sender_spoofing", "tell_adult"],
        learningObjectives: ["Understand phishing tactics and prevention","Recognise fake sender addresses","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // MODULE 4 — Password Castle
  // ─────────────────────────────────────────────────────────
  {
    slug: "password-castle",
    title: "Password Castle",
    subtitle: "Build your defences",
    icon: "🏰",
    color: "#8B5CF6",
    badge: "🔐",
    badgeName: "Lock Keeper",
    order: 4,
    lessons: [
      // ── GROUP A ──
      {
        stepId: "a-module-intro-4",
        type: "story",
        title: "The castle gate",
        ageGroup: "A",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Captain Cyber's castle had a flimsy gate. Anyone could push it open. A password is like a castle gate — if it is weak, intruders can get in. In this module, you will build a Password Castle with locks so strong only YOU can open them.",
        icon: "🏰",
        mascot: "🦸",
        speech: "A strong password is the first line of defence. Let's build your castle!",
        conceptKeys: ["password_strength", "module_intro"],
        learningObjectives: ["Create and maintain strong passwords","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-cross-module-review-3",
        type: "quiz",
        title: "Review: Phishing Fisher",
        ageGroup: "A",
        stepCategory: "review",
        depthLevel: 2,
        question: "From Module 3: you get a message saying 'Click here to win a free game!' What do you do?",
        options: [
          "Click it immediately",
          "Ask a grown-up first",
          "Share it with friends"
        ],
        answer: 1,
        explanation: "Free prize messages are often scams. Always check with a grown-up first.",
        icon: "🎣",
        conceptKeys: ["phishing_hooks", "suspicious_links", "tell_adult"],
        learningObjectives: ["Recognise bait messages and fake offers","Identify and avoid dangerous links","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-what-is-password",
        type: "story",
        title: "What is a password?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "A password is a secret word or phrase that proves it is really you. It is like the key to your diary or the code to your bike lock. You would not give your diary key to a stranger — do not share your password either!",
        icon: "🔑",
        mascot: "🦸",
        speech: "Passwords are secret keys. Keep them safe and secret!",
        conceptKeys: ["password_basics"],
        learningObjectives: ["Understand what passwords are and why they matter"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-password-rules",
        type: "quiz",
        title: "Password rules",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        question: "Which password is stronger?",
        options: [
          "123456",
          "MyNameIsSam",
          "Blue$Mountain42!",
        ],
        answer: 2,
        explanation: "Strong passwords mix letters, numbers, and symbols. Short or guessable passwords are easy to break.",
        icon: "💪",
        conceptKeys: ["password_strength"],
        learningObjectives: ["Create and maintain strong passwords"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-do-not-share",
        type: "story",
        title: "Do not share!",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "Even your best friend should not know your password. If someone asks for it, say no and tell a grown-up. Real friends respect your secrets.",
        icon: "🤐",
        mascot: "🦸",
        speech: "Your password is YOUR business. Never share it.",
        conceptKeys: ["password_sharing"],
        learningObjectives: ["Never share passwords with anyone"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-password-manager-intro",
        type: "story",
        title: "Password helpers",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        text: "Remembering lots of passwords is hard. Grown-ups use a password manager — like a treasure chest that keeps all your keys safe. You only need to remember ONE strong password to open it.",
        icon: "🗝️",
        mascot: "🦸",
        speech: "A password manager is like a super-secure treasure chest for your keys.",
        conceptKeys: ["password_manager"],
        learningObjectives: ["Use a password manager securely"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-password-match",
        type: "quiz",
        title: "Password match",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        question: "Your sibling asks for your password so they can play your game. What do you do?",
        options: [
          "Give it to them",
          "Say no and tell a grown-up",
          "Change it after they finish"
        ],
        answer: 1,
        explanation: "Never share your password, even with family. Ask a grown-up to help instead.",
        icon: "🚫",
        conceptKeys: ["password_sharing", "tell_adult"],
        learningObjectives: ["Never share passwords with anyone","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.a","ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-module4-review",
        type: "quiz",
        title: "Module 4 review",
        ageGroup: "A",
        stepCategory: "review",
        depthLevel: 3,
        question: "What makes a strong password?",
        options: [
          "Your name or birthday",
          "A mix of letters, numbers, and symbols",
          "A short, easy word"
        ],
        answer: 1,
        explanation: "Mix letters, numbers, and symbols. Personal info is easy for hackers to guess.",
        icon: "📝",
        conceptKeys: ["password_strength", "password_basics"],
        learningObjectives: ["Create and maintain strong passwords","Understand what passwords are and why they matter"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "a-module4-bridge",
        type: "story",
        title: "Your real-world mission",
        ageGroup: "A",
        stepCategory: "bridge",
        depthLevel: 4,
        text: "Tonight, with a grown-up, check one of your accounts. Ask: 'Is our password strong?' If it is weak, change it TOGETHER. Share your Password Castle progress with Captain Cyber!",
        icon: "🔍",
        mascot: "🦸",
        speech: "Building a strong password together is a great team mission.",
        conceptKeys: ["password_strength", "password_manager", "real_world_bridge"],
        learningObjectives: ["Create and maintain strong passwords","Use a password manager securely","Connect online learning to offline habits"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a-module4-capstone",
        type: "quiz",
        title: "Lock Keeper quiz",
        ageGroup: "A",
        stepCategory: "capstone",
        depthLevel: 4,
        question: "You receive a message: 'Enter your password here to get free gems for your game.' What do you do?",
        options: [
          "Enter it — free gems!",
          "Close the message and tell a grown-up",
          "Enter just the first part"
        ],
        answer: 1,
        explanation: "Free offers that ask for passwords are traps. Never enter your password for a 'free' reward.",
        icon: "🏆",
        conceptKeys: ["password_strength", "phishing_hooks", "tell_adult"],
        learningObjectives: ["Create and maintain strong passwords","Recognise bait messages and fake offers","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b","ISTE 1.3.d"],
        activityType: "warm-retry-quiz",
      },
      // ── GROUP B ──
      {
        stepId: "b-module-intro-4",
        type: "story",
        title: "The cracked gate",
        ageGroup: "B",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Captain Cyber's castle gate had a combination lock. The problem? The combination was 1-2-3-4. Any intruder could guess it in seconds. In this module, you will learn why weak passwords are cracked gates and how to build a vault no intruder can open.",
        icon: "🏰",
        mascot: "🦸",
        speech: "A strong password is the strongest wall in your digital castle.",
        conceptKeys: ["password_strength", "password_basics", "module_intro"],
        learningObjectives: ["Create and maintain strong passwords","Understand what passwords are and why they matter","Understand the module theme and goals"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-cross-module-review-3",
        type: "quiz",
        title: "Review: Phishing Fisher",
        ageGroup: "B",
        stepCategory: "review",
        depthLevel: 2,
        question: "From Module 3: you see a link that looks like your school site but the domain is wrong. What should you do?",
        options: [
          "Click it anyway",
          "Do not click and tell a trusted adult",
          "Share the link with friends"
        ],
        answer: 1,
        explanation: "A wrong domain means danger. Never click suspicious links.",
        icon: "🎣",
        conceptKeys: ["suspicious_links", "phishing_hooks", "tell_adult"],
        learningObjectives: ["Identify and avoid dangerous links","Recognise bait messages and fake offers","Know when and how to ask a trusted adult for help"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-password-cracking",
        type: "story",
        title: "How passwords get cracked",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 2,
        text: "Hackers use 'dictionary attacks' — they try thousands of common words in seconds. 'Password', '123456', and your pet's name can all be guessed. A strong password must be long, random, and unique.",
        icon: "🔓",
        mascot: "🦸",
        speech: "If it is in a dictionary, a hacker can crack it. Be unpredictable.",
        conceptKeys: ["password_strength", "password_basics"],
        learningObjectives: ["Create and maintain strong passwords","Understand what passwords are and why they matter"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-password-rules-b",
        type: "quiz",
        title: "Password forensics",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        question: "Which password would be hardest for a hacker to crack?",
        options: [
          "bella2010",
          "Tr0ub4dor&3",
          "jessica"
        ],
        answer: 1,
        explanation: "Mix upper/lowercase, numbers, and symbols. Avoid names, dates, or dictionary words.",
        icon: "🔍",
        conceptKeys: ["password_strength"],
        learningObjectives: ["Create and maintain strong passwords"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-password-reuse",
        type: "story",
        title: "Password reuse risk",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "Using the same password for everything is like using ONE key for your house, your bike, and your school locker. If someone steals one key, they get everything. Every site needs its own unique password.",
        icon: "🔑",
        mascot: "🦸",
        speech: "One key for everything is a disaster waiting to happen.",
        conceptKeys: ["password_reuse"],
        learningObjectives: ["Understand risks of reusing passwords"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-two-factor-intro",
        type: "story",
        title: "Two-factor defence",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        text: "Two-factor authentication (2FA) is like a castle with TWO gates. Even if someone steals your key, they still cannot get in without the second gate (usually a code sent to your phone). Always turn it on when you can.",
        icon: "🔐",
        mascot: "🦸",
        speech: "2FA adds a second lock. Hackers hate it.",
        conceptKeys: ["two_factor_auth"],
        learningObjectives: ["Use 2FA for account security"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-password-leak",
        type: "quiz",
        title: "The password leak",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        question: "You read that a website you use had a 'data breach' and passwords were stolen. What do you do?",
        options: [
          "Nothing — it is not your fault",
          "Change that password immediately, and change any other site where you used the same one",
          "Tell everyone their passwords were stolen"
        ],
        answer: 1,
        explanation: "Change the compromised password and any duplicates. Password reuse multiplies the damage.",
        icon: "⚠️",
        conceptKeys: ["password_reuse", "data_breach_response"],
        learningObjectives: ["Understand risks of reusing passwords","Respond correctly to service breaches"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-password-boss",
        type: "story",
        title: "The Password Castle boss",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 5,
        text: "The boss level: a site requires at least 12 characters, mixed case, numbers, symbols, no dictionary words, and a unique password. This is what real security looks like. Build your castle to these standards.",
        icon: "👑",
        mascot: "🦸",
        speech: "The strongest castles have the strongest gates.",
        conceptKeys: ["password_strength", "password_reuse", "two_factor_auth"],
        learningObjectives: ["Create and maintain strong passwords","Understand risks of reusing passwords","Use 2FA for account security"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-module4-review",
        type: "quiz",
        title: "Module 4 review",
        ageGroup: "B",
        stepCategory: "review",
        depthLevel: 3,
        question: "Why is password reuse dangerous?",
        options: [
          "It makes your computer slower",
          "One breach exposes all your accounts",
          "It is not dangerous at all"
        ],
        answer: 1,
        explanation: "If one site is breached and you reused the password, attackers can access every other site too.",
        icon: "📝",
        conceptKeys: ["password_reuse", "data_breach_response"],
        learningObjectives: ["Understand risks of reusing passwords","Respond correctly to service breaches"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "warm-retry-quiz",
      },
      {
        stepId: "b-module4-bridge",
        type: "story",
        title: "Real-world mission",
        ageGroup: "B",
        stepCategory: "bridge",
        depthLevel: 4,
        text: "With a parent, review your password habits. Do you reuse passwords? Do you have 2FA turned on? Pick ONE account to strengthen this week and report back to Captain Cyber.",
        icon: "🔍",
        mascot: "🦸",
        speech: "Small improvements to your digital habits make a huge difference.",
        conceptKeys: ["password_strength", "password_reuse", "two_factor_auth", "real_world_bridge"],
        learningObjectives: ["Create and maintain strong passwords","Understand risks of reusing passwords","Use 2FA for account security","Connect online learning to offline habits"],
        successCriteria: ["Kid can apply the concept in this step"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "b-module4-capstone",
        type: "quiz",
        title: "Lock Keeper exam",
        ageGroup: "B",
        stepCategory: "capstone",
        depthLevel: 5,
        question: "You use the same password for your game account, email, and social media. Your game account gets hacked. What happens?",
        options: [
          "Only your game account is affected",
          "The hacker can try the same password on your email and social media",
          "Your password resets automatically"
        ],
        answer: 1,
        explanation: "Password reuse means one breach becomes many. Always use unique passwords per site.",
        icon: "🏆",
        conceptKeys: ["password_reuse", "data_breach_response", "password_strength"],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // MODULE 5 — Privacy Shield
  // ─────────────────────────────────────────────────────────
  {
    slug: "privacy-shield",
    title: "Privacy Shield",
    subtitle: "Guard your secrets",
    icon: "🛡️",
    color: "#F59E0B",
    badge: "🔒",
    badgeName: "Secret Guardian",
    order: 5,
    lessons: [
      // ── GROUP A ──
      {
        stepId: "a5-what-is-private",
        type: "story",
        title: "What is private?",
        ageGroup: "A",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Your name, address, school, phone number, and photos with your face are private information. They are like treasure — you should only share them with people you trust, like your parents or teacher.",
        icon: "🛡️",
        mascot: "🦸",
        speech: "Personal info is private treasure. Guard it closely!",
        conceptKeys: ["private_info", "oversharing"],
        learningObjectives: ["Identify private information", "Understand why some details must be protected"],
        successCriteria: ["Kid can name 3 private details", "Kid says 'tell an adult' when unsure"],
        connexusStandards: ["ISTE 1.2.a", "ISTE 1.2.b"],
        activityType: "story-led-mascot",
      },
      {
        stepId: "a5-safe-to-share",
        type: "quiz",
        title: "Safe to share?",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        question: "Which of these is safe to share with someone online?",
        options: [
          "Your favourite colour",
          "Your home address",
          "Your school name"
        ],
        answer: 0,
        explanation: "Your favourite colour is safe to share. Your address and school are private.",
        icon: "✅",
        conceptKeys: ["private_info", "oversharing"],
        learningObjectives: ["Classify information as safe or private"],
        successCriteria: ["Kid correctly identifies safe vs private info 3/3 times"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "point-to-identify",
      },
      {
        stepId: "a5-strangers-online",
        type: "story",
        title: "Strangers online",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 2,
        text: "A stranger in a chat asks for your photo. What do you do? Captain Cyber says: say no, block them, and find a trusted adult. You do not owe strangers any pictures or information.",
        icon: "🚫",
        mascot: "🦸",
        speech: "Say no to strangers. Block and tell an adult.",
        conceptKeys: ["stranger_danger", "photo_privacy", "tell_adult"],
        learningObjectives: ["Recognise stranger requests", "Practice the no-block-tell response"],
        successCriteria: ["Kid can verbalise the no-block-tell sequence"],
        connexusStandards: ["ISTE 1.2.a", "ISTE 1.3.d"],
        activityType: "branching-response",
      },
      {
        stepId: "a5-shield-building",
        type: "story",
        title: "Your shield is strong",
        ageGroup: "A",
        stepCategory: "core",
        depthLevel: 3,
        text: "Tap to add protections to your Privacy Shield: lock your profile, turn off location, and keep personal details secret. A strong shield keeps you safe while you explore.",
        icon: "🛡️",
        mascot: "🦸",
        speech: "Tap, tap, tap — your shield is getting stronger!",
        conceptKeys: ["privacy_settings", "private_info"],
        learningObjectives: ["Identify privacy settings", "Understand how settings protect you"],
        successCriteria: ["Kid can name 2 privacy settings"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "interactive-shield-build",
        materials: ["tablet or desktop"],
      },
      {
        stepId: "a5-captain-cyber-quiz",
        type: "quiz",
        title: "Captain Cyber quiz",
        ageGroup: "A",
        stepCategory: "capstone",
        depthLevel: 3,
        question: "Which of these should you NEVER share with someone you meet online?",
        options: [
          "Your favourite game",
          "A photo of your face",
          "Your favourite colour"
        ],
        answer: 1,
        explanation: "Never share photos of yourself with strangers. Tell an adult if someone asks.",
        icon: "🏆",
        conceptKeys: ["private_info", "photo_privacy", "tell_adult"],
        learningObjectives: ["Review all Module 5 concepts", "Demonstrate retention"],
        successCriteria: ["Score 3/3 on capstone quiz"],
        connexusStandards: ["ISTE 1.2.a"],
        activityType: "warm-retry-quiz",
      },
      // ── GROUP B ──
      {
        stepId: "b-cross-module-review-5",
        type: "quiz",
        title: "Review: Password Castle",
        ageGroup: "B",
        stepCategory: "review",
        depthLevel: 2,
        question: "From Module 4: why is password reuse dangerous?",
        options: [
          "It makes your account look boring",
          "One breach exposes all accounts",
          "It is not dangerous"
        ],
        answer: 1,
        explanation: "Reuse multiplies risk. One breach becomes many.",
        icon: "🏰",
        conceptKeys: ["password_reuse", "data_breach_response"],
        connexusStandards: ["ISTE 1.2.b"],
      },
      {
        stepId: "b5-digital-footprint",
        type: "story",
        title: "The digital footprint",
        ageGroup: "B",
        stepCategory: "intro",
        depthLevel: 1,
        text: "Everything you post is archived. A post at age 10 can be seen at 16 — by future teachers, coaches, and colleges. Your digital footprint is permanent. Before you post, ask: 'Would I be comfortable with everyone seeing this forever?'",
        icon: "👣",
        mascot: "🦸",
        speech: "Your footprint lasts longer than you think. Think before you post.",
        conceptKeys: ["digital_footprint", "data_footprint"],
        learningObjectives: ["Understand permanence of online posts", "Connect present actions to future consequences"],
        successCriteria: ["Kid can explain why a post at 10 matters at 16"],
        connexusStandards: ["ISTE 1.2.b", "ISTE 1.3.d"],
        activityType: "narrative-scenario",
      },
      {
        stepId: "b5-what-is-private-b",
        type: "quiz",
        title: "What is private?",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 2,
        question: "Which combination could help a stranger find you in real life?",
        options: [
          "Your favourite food",
          "Your school, city, and team name",
          "Your favourite YouTuber"
        ],
        answer: 1,
        explanation: "School + city + team can pinpoint your location. Keep details vague.",
        icon: "📍",
        conceptKeys: ["private_info", "location_safety"],
        learningObjectives: ["Classify PII granularly", "Understand location risks"],
        successCriteria: ["Kid correctly identifies location-pinpointing combinations"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "multi-select-partial-credit",
      },
      {
        stepId: "b5-grooming-arc",
        type: "story",
        title: "The grooming arc",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "A 'nice' stranger starts with friendly chats, then asks for photos, then asks to keep secrets. This is grooming. Real friends never ask you to keep secrets from your parents. If someone tries this, block and tell an adult immediately.",
        icon: "🎭",
        mascot: "🦸",
        speech: "Grooming starts small. Trust your gut and tell an adult.",
        conceptKeys: ["grooming_awareness", "manipulation_tactics"],
        learningObjectives: ["Recognise grooming patterns", "Understand manipulation stages"],
        successCriteria: ["Kid can name 2 grooming stages"],
        connexusStandards: ["ISTE 1.3.d", "ISTE 1.2.a"],
        activityType: "branching-consequence",
        choices: [
          {
            text: "Share a photo because they seem nice",
            feedback: "Groomers start with small requests. Sharing a photo is a red flag.",
            consequence: "negative",
            xpDelta: -5,
          },
          {
            text: "Block and tell a trusted adult",
            feedback: "You recognised the pattern. Protecting yourself is the right move.",
            consequence: "positive",
            xpDelta: 10,
          },
          {
            text: "Keep it a secret because they said no one else would understand",
            feedback: "Secrets from parents are a major grooming warning sign.",
            consequence: "negative",
            xpDelta: -5,
          },
        ],
      },
      {
        stepId: "b5-share-with-whom",
        type: "quiz",
        title: "Share-with-whom matrix",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        question: "Your school address is safe to share with:",
        options: [
          "A stranger in a game",
          "Your parent or teacher",
          "A new friend you met online"
        ],
        answer: 1,
        explanation: "Only trusted adults need your school address. Never share it with strangers or online friends.",
        icon: "📊",
        conceptKeys: ["private_info", "oversharing", "trusted_adults"],
        learningObjectives: ["Map information to audience trust levels", "Apply the share-with-whom matrix"],
        successCriteria: ["Kid correctly classifies 4/4 scenarios"],
        connexusStandards: ["ISTE 1.2.b", "ISTE 1.3.d"],
        activityType: "grid-classification",
      },
      {
        stepId: "b5-location-risks",
        type: "story",
        title: "Location risks",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 3,
        text: "Captain Cyber accidentally posted a photo with location tagging on. His exact address was visible to everyone. Geo-tagging can reveal your school or home. Always turn off location tagging for photos, or ask a grown-up to check.",
        icon: "📍",
        mascot: "🦸",
        speech: "A photo can broadcast your address. Turn off geotagging.",
        conceptKeys: ["geotagging", "location_safety", "photo_privacy"],
        learningObjectives: ["Understand hidden location data in photos", "Learn to disable geo-tagging"],
        successCriteria: ["Kid can explain what geo-tagging is and how to turn it off"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "narrative-scenario",
        materials: ["smartphone or tablet"],
      },
      {
        stepId: "b5-settings-challenge",
        type: "quiz",
        title: "Settings challenge",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        question: "You want to turn off location sharing on your phone. Where do you go?",
        options: [
          "Settings > Privacy > Location Services",
          "Home screen",
          "Messages app"
        ],
        answer: 0,
        explanation: "Location settings live under Privacy. A grown-up can help you find them.",
        icon: "⚙️",
        conceptKeys: ["privacy_settings", "location_safety"],
        learningObjectives: ["Navigate device privacy settings", "Turn off location sharing"],
        successCriteria: ["Kid can locate location settings with adult help"],
        connexusStandards: ["ISTE 1.2.b"],
        activityType: "simulated-ui",
        materials: ["smartphone or tablet"],
      },
      {
        stepId: "b5-privacy-plan",
        type: "challenge",
        title: "Privacy plan",
        ageGroup: "B",
        stepCategory: "core",
        depthLevel: 4,
        text: "Design your own Privacy Shield. Choose 3 rules you will follow: who you share info with, what you post, and how you handle strangers. Your plan is stored as 'my shield' — review it weekly.",
        icon: "🛡️",
        conceptKeys: ["privacy_settings", "private_info", "oversharing", "real_world_bridge"],
        learningObjectives: ["Create a personal privacy plan", "Commit to safe sharing habits"],
        successCriteria: ["Kid completes 3-rule privacy plan"],
        connexusStandards: ["ISTE 1.3.d", "ISTE 1.2.a"],
        activityType: "plan-builder",
      },
      {
        stepId: "b5-final-exam",
        type: "challenge",
        title: "Final exam",
        ageGroup: "B",
        stepCategory: "capstone",
        depthLevel: 5,
        text: "Mixed exam from all 5 modules: cyberbullying response, phishing detection, password strength, and privacy scenarios. 12 questions, timed. Score determines your league XP and badge.",
        icon: "🏆",
        conceptKeys: ["cyberbullying_response", "phishing_hooks", "password_strength", "private_info", "digital_footprint"],
        learningObjectives: ["Demonstrate mastery across all modules", "Apply knowledge under timed conditions"],
        successCriteria: ["Score ≥ 70% on final exam"],
        connexusStandards: ["ISTE 1.2.a", "ISTE 1.2.b", "ISTE 1.3.d"],
        activityType: "timed-exam",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // GRADUATION — End of Programme
  // ─────────────────────────────────────────────────────────
  {
    slug: "cyber-guardian-graduation",
    title: "Cyber Guardian Graduation",
    subtitle: "You did it!",
    icon: "🎓",
    color: "#10B981",
    badge: "🎓",
    badgeName: "Cyber Guardian",
    order: 6,
    lessons: [
      // ── GROUP A ──
      {
        stepId: "a-graduation-story",
        type: "story",
        title: "Captain Cyber's secret mission",
        ageGroup: "A",
        stepCategory: "capstone",
        depthLevel: 4,
        text: "Captain Cyber is proud of you! You have learned about personal information, cyberbullying, phishing, passwords, and privacy. Now you are a Cyber Safe Explorer. Your certificate is waiting, and so is a special secret mission from Captain Cyber.",
        icon: "🎓",
        mascot: "🦸",
        speech: "You are now a Cyber Safe Explorer! Keep exploring safely.",
        conceptKeys: ["graduation", "module_intro", "badge_earned"],
        learningObjectives: ["Celebrate completion of all 5 modules", "Reinforce identity as a safe explorer"],
        successCriteria: ["Kid receives Explorer badge and certificate"],
        connexusStandards: ["ISTE 1.3.d"],
        activityType: "celebration-narrative",
      },
      // ── GROUP B ──
      {
        stepId: "b-graduation-challenge",
        type: "challenge",
        title: "Classroom Champion round",
        ageGroup: "B",
        stepCategory: "capstone",
        depthLevel: 6,
        text: "You have completed all 5 modules. You are now a Cyber Guardian. Take this final challenge to earn your badge, certificate, and a spot on the Classroom Champion leaderboard.",
        icon: "🏆",
        conceptKeys: ["graduation", "module_intro", "badge_earned", "leaderboard"],
        learningObjectives: ["Demonstrate mastery across all 5 modules", "Earn Cyber Guardian status"],
        successCriteria: ["Score ≥ 80% on final challenge", "Earn Cyber Guardian badge"],
        connexusStandards: ["ISTE 1.2.a", "ISTE 1.2.b", "ISTE 1.3.d"],
        activityType: "live-competitive-round",
      },
    ],
  },
];

