import re

with open("src/seeders/curriculumSeed.ts", "r", encoding="utf-8") as f:
    content = f.read()

# Section-specific question replacements
replacements = [
    # a-online-safety section - Online Safety Basics
    (r'question: "Which of these is personal information\?"',
     'question: "Which piece of information could a hacker use to steal your online account?"'),
    (r'question: "Which is safest to share online with a class friend\?"',
     'question: "In an online game, which detail is safest to share with a teammate you just met?"'),
    (r'question: "What does a password help protect\?"',
     'question: "Why do scammers want to steal your password?"'),
    (r'question: "Which information should you keep private online\?"',
     'question: "A message asks for your address and birthday. What should you do first?"'),
    (r'question: "If a game asks for your real name and address, what should you do first\?"',
     'question: "If a website asks for your login details and you did not create an account there, what should you do?"'),
    (r'question: "What should you do if someone you do not know messages you online\?"',
     'question: "A stranger sends you a link that says Free gems! What is the safest action?"'),
    (r'question: "What is the safest action when you see a pop-up that says you won a prize\?"',
     'question: "You get an email saying your account will be deleted in 1 hour unless you click a link. What do you do?"'),
    (r'question: "Which is a strong password\?"',
     'question: "Which password would be hardest for a hacker to guess?"'),
    (r'question: "Why should you not share your password with friends\?"',
     'question: "Why is sharing your password with a friend risky, even if you trust them?"'),
    (r'question: "What does two-factor authentication do\?"',
     'question: "What does two-factor authentication (2FA) help prevent?"'),
    (r'question: "Which action helps keep your device safe from malware\?"',
     'question: "Which action helps keep your device safe from malware and spyware?"'),
    (r'question: "What should you do before downloading a new app\?"',
     'question: "Before installing a free app from an unknown website, what should you check first?"'),
    (r'question: "What is phishing\?"',
     'question: "What is phishing in the context of cybercrime?"'),
    (r'question: "Which message is most likely a phishing attempt\?"',
     'question: "Which message is most likely a phishing attempt?"'),
    (r'question: "What should you do if you click a suspicious link by accident\?"',
     'question: "You accidentally entered your password on a fake login page. What should you do next?"'),
    (r'question: "Which website URL is safest to trust\?"',
     'question: "Which website URL is safest to trust when logging into your school account?"'),
    (r'question: "What does a padlock icon in the browser mean\?"',
     'question: "What does the padlock icon in the browser address bar tell you about a website?"'),
    (r'question: "What is a cyberbully\?"',
     'question: "What is a cyberbully?"'),
    (r'question: "If you see a mean post about a classmate, what should you do\?"',
     'question: "If you see a fake account posting embarrassing photos of a classmate, what should you do?"'),
    (r'question: "Which is the best thing to do if someone is mean to you online\?"',
     'question: "Someone keeps sending you mean messages online. What is the best first step?"'),
    (r'question: "Why is it dangerous to meet an online friend in person without telling an adult\?"',
     'question: "Why is it dangerous to meet an online friend in person without telling a trusted adult?"'),
    (r'question: "What does digital footprint mean\?"',
     'question: "What does digital footprint mean in the context of cybercrime?"'),
    (r'question: "Which post could harm your digital footprint\?"',
     'question: "Which post could harm your digital footprint and be used by scammers later?"'),
    (r'question: "Why should you think before you post\?"',
     'question: "Why should you think before you post, even if you delete it later?"'),
    (r'question: "What can you do to control your privacy on social media\?"',
     'question: "What can you do to control your privacy on social media and limit what scammers can see?"'),
    (r'question: "Which rule is most important in a group chat\?"',
     'question: "Which rule is most important in a group chat to prevent cyberbullying?"'),
    (r'question: "Why should you ask before screenshotting and sharing someones message\?"',
     'question: "Why should you ask before screenshotting and sharing someones private message?"'),
    (r'question: "What should you do if you receive a mean message\?"',
     'question: "You receive a threatening message from an anonymous account. What should you do first?"'),
    (r'question: "Which is a sign of a fake account\?"',
     'question: "Which is a sign of a fake account that might be a scammer or cyberbully?"'),
    (r'question: "What is the safest way to handle a suspicious email\?"',
     'question: "What is the safest way to handle a suspicious email asking for your password?"'),
    (r'question: "Why do scammers create fake websites\?"',
     'question: "Why do scammers create fake websites that look like real ones?"'),
    (r'question: "Which action is a red flag for identity theft\?"',
     'question: "Which action is a red flag that someone might be trying to steal your identity?"'),
    (r'question: "What is social engineering\?"',
     'question: "What is social engineering in cybercrime?"'),
    (r'question: "Which phrase creates urgency to trick you\?"',
     'question: "Which phrase creates urgency to trick you into acting without thinking?"'),
    (r'question: "What should you do if a message claims you won a contest you never entered\?"',
     'question: "What should you do if a message claims you won a contest you never entered?"'),
    (r'question: "Which step helps verify if an email is real\?"',
     'question: "Which step helps verify if an email from your bank is real or a phishing attempt?"'),
    (r'question: "What is the first thing to do after clicking a suspicious link\?"',
     'question: "What is the first thing to do after clicking a suspicious link and entering your details?"'),
    (r'question: "Which behavior is a sign of grooming\?"',
     'question: "Which online behavior is a warning sign of grooming by a predator?"'),
    (r'question: "Why is location sharing risky with strangers\?"',
     'question: "Why is location sharing risky with strangers online?"'),
    (r'question: "Which file type is most likely to contain malware\?"',
     'question: "Which file type is most likely to contain malware from an unknown sender?"'),
    (r'question: "What does ransomware do\?"',
     'question: "What does ransomware do to your device or files?"'),
    (r'question: "What is a deepfake\?"',
     'question: "What is a deepfake and why is it dangerous in cybercrime?"'),
    (r'question: "How can you spot a manipulated video\?"',
     'question: "How can you spot a manipulated video or deepfake online?"'),
    (r'question: "Why is it important to verify information before sharing\?"',
     'question: "Why is it important to verify information before sharing, especially with deepfakes?"'),
    (r'question: "Which platform setting controls who sees your posts\?"',
     'question: "Which platform setting helps control who sees your posts and protects from scammers?"'),
    (r'question: "What is sextortion\?"',
     'question: "What is sextortion in the context of cybercrime?"'),
    (r'question: "If someone threatens to share your private photos, what should you do\?"',
     'question: "If someone threatens to share your private photos unless you pay, what should you do?"'),
    (r'question: "Why should you use different passwords for different accounts\?"',
     'question: "Why should you use different passwords for different accounts?"'),
    (r'question: "Which is the safest way to create a password\?"',
     'question: "Which is the safest way to create a password that hackers cannot guess?"'),
    (r'question: "What does a data breach mean\?"',
     'question: "What does a data breach mean and why should you care?"'),
    (r'question: "Which is an example of a phishing email\?"',
     'question: "Which is an example of a phishing email?"'),
    (r'question: "What should you do if a friends account sends you a strange link\?"',
     'question: "What should you do if a friends account sends you a strange link?"'),
]

for pattern, replacement in replacements:
    content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)

# Fix common wrong answers to make more sense
answer_fixes = [
    (r'wrongs: \[\["Ignore the message", "Share it with friends", "Reply with personal details"\]\]',
     'wrongs: ["Reply with personal details", "Share it with friends", "Ignore the warning"]'),
    (r'wrongs: \[\["Ignore the message", "Share it with friends", "Reply with more details"\]\]',
     'wrongs: ["Reply with more details", "Share it with friends", "Ignore the warning"]'),
    (r'wrongs: \[\["Ignore it", "Share it publicly", "Reply with anger"\]\]',
     'wrongs: ["Reply with anger", "Share it publicly", "Ignore it"]'),
    (r'wrongs: \[\["Share it everywhere", "Ignore it", "Reply with insults"\]\]',
     'wrongs: ["Reply with insults", "Share it everywhere", "Ignore it"]'),
    (r'wrongs: \[\["Forward it", "Share it", "Ignore it"\]\]',
     'wrongs: ["Share it", "Forward it", "Ignore it"]'),
    (r'wrongs: \[\["Post it", "Share it", "Ignore it"\]\]',
     'wrongs: ["Share it", "Post it", "Ignore it"]'),
    (r'wrongs: \[\["Click it", "Share it", "Ignore it"\]\]',
     'wrongs: ["Share it", "Click it", "Ignore it"]'),
]

for pattern, replacement in answer_fixes:
    content = content.replace(pattern, replacement)

with open("src/seeders/curriculumSeed.ts", "w", encoding="utf-8") as f:
    f.write(content)

print("Curriculum content updated with cybercrime-specific questions")
